from flask import Flask, render_template, request
import pickle
import random
import string
import requests
import os
import numpy as np

app = Flask(__name__)

# Configuration
BASE_SHORT_DOMAIN = "http://short.ly/"

# 1. LOAD THE "SUPER" ASSETS
# These must be the files generated by your new Training Script (C=0.05 version)
try:
    model = pickle.load(open("logic_model.pkl", "rb"))
    vectorizer = pickle.load(open("vectorizer.pkl", "rb"))
except FileNotFoundError:
    print("Error: logic_model.pkl or vectorizer.pkl not found. Run the training script first!")

# Load mapping for the shortener
if os.path.exists("short_url_mapping.pkl"):
    short_url_mapping = pickle.load(open("short_url_mapping.pkl", "rb"))
else:
    short_url_mapping = {}

# --- HELPER FUNCTIONS ---

def generate_short_code(length=6):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

def expand_url(url):
    """
    Checks if a URL is a redirect/shortlink and finds the real destination.
    This ensures the model scans the 'hidden' URL.
    """
    try:
        # We use a timeout so the app doesn't freeze on broken links
        response = requests.head(url, allow_redirects=True, timeout=2)
        return response.url
    except:
        return url

# --- ROUTES ---

@app.route('/')
def home():
    return render_template("index.html")

@app.route('/shorten', methods=['POST'])
def shorten():
    original_url = request.form['original_url'].strip()
    short_code = generate_short_code()
    short_url = BASE_SHORT_DOMAIN + short_code

    # Save to memory and disk
    short_url_mapping[short_url] = original_url
    pickle.dump(short_url_mapping, open("short_url_mapping.pkl", "wb"))

    return render_template("index.html", generated_short=short_url)

@app.route('/predict', methods=['POST'])
def predict():
    user_url = request.form['url'].strip()

    # Step 1: Expand URL (Look behind the curtain)
    # If it's a link we shortened ourselves, get it from our dictionary.
    # Otherwise, try to expand it using the web.
    if user_url in short_url_mapping:
        target_url = short_url_mapping[user_url]
    else:
        target_url = expand_url(user_url)

    # Step 2: Transform & Predict
    # The vectorizer converts the string into the 1500 math features
    url_vectorized = vectorizer.transform([target_url])
    
    # Logistic Regression gives us a 0 (Benign) or 1 (Malicious)
    prediction = model.predict(url_vectorized)[0]

    # Step 3: Result Formatting
    if prediction == 1:
        result = "Malicious URL ⚠️"
        css_class = "malicious"
    else:
        result = "Benign URL ✅"
        css_class = "benign"

    return render_template(
        "index.html", 
        prediction_text=result, 
        original_url=target_url,
        status_class=css_class
    )

if __name__ == "__main__":
    app.run(debug=True)